In [3]:
import pandas as pd
df= pd.read_csv('pokemon.csv')

print(df)

##read header
df.columns

##read each row 
#print(df.iloc[0:4])



##read a specific location(R,C)
#print(Df.iloc[2,1])

       #                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49
1      2                Ivysaur    Grass  Poison    405  60      62       63
2      3               Venusaur    Grass  Poison    525  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123
4      4             Charmander     Fire     NaN    309  39      52       43
..   ...                    ...      ...     ...    ...  ..     ...      ...
795  719                Diancie     Rock   Fairy    600  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60
799  721              Volcanion     Fire   Water    600  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 13 columns]
0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [4]:
##read each column
print(df[['Name', 'Type 1', 'HP']])

                      Name   Type 1  HP
0                Bulbasaur    Grass  45
1                  Ivysaur    Grass  60
2                 Venusaur    Grass  80
3    VenusaurMega Venusaur    Grass  80
4               Charmander     Fire  39
..                     ...      ...  ..
795                Diancie     Rock  50
796    DiancieMega Diancie     Rock  50
797    HoopaHoopa Confined  Psychic  80
798     HoopaHoopa Unbound  Psychic  80
799              Volcanion     Fire  80

[800 rows x 3 columns]

In [8]:
## Read each Row
print(df.iloc[0:4])

   #                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49
1  2                Ivysaur  Grass  Poison    405  60      62       63
2  3               Venusaur  Grass  Poison    525  80      82       83
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123

   Sp. Atk  Sp. Def  Speed  Generation  Legendary
0       65       65     45           1      False
1       80       80     60           1      False
2      100      100     80           1      False
3      122      120     80           1      False

In [16]:
## read  a specific location(R,C)
#print(df.iloc[2,1])
#for index, row in df.iterrows():
   # print(index,row['Name'])
df.loc[df['Type 1']== "Fire"]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,505,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,350,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,410,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,500,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,495,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,525,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,309,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,405,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,534,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,250,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,410,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,365,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,580,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,310,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,405,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,530,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,305,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,460,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,470,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,309,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,405,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,534,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,540,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,600,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,308,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,528,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,316,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,498,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,315,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,480,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,484,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,307,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,409,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,534,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,382,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,499,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,369,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [21]:
df.sort_values(['Type 1','HP'], ascending=[1,0])

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,515,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,550,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,500,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,495,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,325,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,295,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,340,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,200,20,15,20,10,55,80,3,False

In [9]:
#df['Total']=df['HP']+ df['Attack']+ df['Defense']+ df['Sp. Atk']+ df['Sp. Def']+ df['Speed']
#df=df.drop(columns=['Total'])
import pandas as pd 
df= pd.read_csv('pokemon.csv')

df['Total'] = df.iloc[:, 4:9].sum(axis=1)
cols=list(df.columns.values)
df[cols[0:4] + [cols[-1]]+cols[4:12]]

    
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,526,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,670,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,870,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,1050,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,503,39,52,43,60,50,65,1,False

In [28]:
45+49+49+65+65+45

318

In [10]:
df.to_csv('modified.csv')

In [31]:
#new_df=df.loc[(df['Type 1']=='Grass') & (df['Type 2']== 'Poison') & (df['HP']>70)]

#new_df.to_csv('filtered.csv')
import re

df.loc[df['Name'].str.contains('^pi[a-z]*', flags =re.I, regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,411,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,577,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,787,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,957,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,500,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,845,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,1005,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,315,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,530,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,790,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,532,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,726,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,455,50,55,50,36,30,43,5,False

In [ ]:
Conditional changes

In [39]:


df = pd.read_csv('filtered.csv')
df.loc[df['Total']>5000,['Generation','Legendary']]='Test Value'
df

,Unnamed: 0,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,2,3,Venusaur,Grass,Poison,870,80,82,83,100,100,80,1,False
1,3,3,VenusaurMega Venusaur,Grass,Poison,1050,80,100,123,122,120,80,1,False
2,50,45,Vileplume,Grass,Poison,840,75,80,85,110,90,50,1,False
3,77,71,Victreebel,Grass,Poison,840,80,105,65,100,70,70,1,False
4,652,591,Amoonguss,Grass,Poison,818,114,85,70,85,80,30,5,False

In [ ]:
Aggregate Statistics(groupby)

In [50]:
df=pd.read_csv('modified.csv')
df['count']=1
df.groupby(['Type 1', 'Type 2']).count()['count']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64